live2d:
  label: 看板娘
  items:
    live2d_modelAPI:
      name: live2d_modelAPI
      label: 看板娘API地址
      type: text
      default: "//live2d.fghrsh.net/api/"
      description: '后台API地址，有能力的可以自己搭建'
    live2d_tipsMessage:
      name: live2d_tipsMessage
      label: 提示语文件地址
      type: text
      default: ""
      description: '提示语地址，不填则默认在live2d插件目录下 /json/***-tips.json'
    live2d_hitokotoAPI:
      name: live2d_hitokotoAPI
      label: 一言API接口
      type: select
      data-type: string
      default: "hitokoto.cn"
      options:
        - value: hitokoto.cn
          label: hitokoto.cn
        - value: lwl12.com
          label: lwl12.com
        - value: jinrishici.com
          label: jinrishici.com（古诗词）
      description: '看板娘静置时的语句，有能力的可以自己搭建'
    live2d_modelId:
      name: live2d_modelId
      label: 默认模型（分组）ID
      type: text
      data-type: long
      default: 1
    live2d_modelTexturesId:
      name: live2d_modelId
      label: 默认材质(模型) ID
      type: text
      data-type: long
      default: 1
    live2d_showToolMenu:
      name: live2d_showToolMenu
      label: 显示工具栏
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 显示
        - value: false
          label: 隐藏
    live2d_canCloseLive2d:
      name: live2d_canCloseLive2d
      label: 关闭看板娘 按钮
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 显示
        - value: false
          label: 隐藏
    live2d_canSwitchModel:
      name: live2d_canSwitchModel
      label: 切换模型 按钮
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 显示
        - value: false
          label: 隐藏
    live2d_canSwitchTextures:
      name: live2d_canSwitchModel
      label: 切换材质 按钮
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 显示
        - value: false
          label: 隐藏
    live2d_canSwitchHitokoto:
      name: live2d_canSwitchHitokoto
      label: 切换一言 按钮
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 显示
        - value: false
          label: 隐藏
    live2d_canTakeScreenshot:
      name: live2d_canTakeScreenshot
      label: 看板娘截图 按钮
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 显示
        - value: false
          label: 隐藏
    live2d_canTurnToHomePage:
      name: live2d_canTurnToHomePage
      label: 返回首页 按钮
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 显示
        - value: false
          label: 隐藏
    live2d_canTurnToAboutPage:
      name: live2d_canTurnToAboutPage
      label: 跳转关于页 按钮
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 显示
        - value: false
          label: 隐藏
    live2d_canTurnToAboutPage:
      name: live2d_canTurnToAboutPage
      label: 跳转关于页 按钮
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 显示
        - value: false
          label: 隐藏
    live2d_modelStorage:
      name: live2d_modelStorage
      label: 记录 ID (刷新后恢复)
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 显示
        - value: false
          label: 隐藏
    live2d_modelRandMode:
      name: live2d_modelRandMode
      label: 模型切换类型
      type: select
      data-type: string
      default: 'rand'
      options:
        - value: 'rand'
          label: 随机
        - value: 'switch'
          label: 顺序
    live2d_modelTexturesRandMode:
      name: live2d_modelTexturesRandMode
      label: 材质切换类型
      type: select
      data-type: string
      default: 'rand'
      options:
        - value: 'rand'
          label: 随机
        - value: 'switch'
          label: 顺序
    live2d_showHitokoto:
      name: live2d_showHitokoto
      label: 空闲时出现一言
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    live2d_showF12Status:
      name: live2d_showF12Status
      label: 控制台显示加载状态
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    live2d_showF12Message:
      name: live2d_showF12Message
      label: 提示消息输出到控制台
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    live2d_showF12OpenMsg:
      name: live2d_showF12OpenMsg
      label: 控制台被打开触发提醒
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    live2d_showCopyMessage:
      name: live2d_showCopyMessage
      label: 内容被复制触发提醒
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    live2d_showWelcomeMessage:
      name: live2d_showWelcomeMessage
      label: 进入面页时显示欢迎语
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    live2d_takagiSize:
      name: live2d_takagiSize
      label: 看板娘大小
      type: text
      data-type: string
      default: "280x250"
    live2d_takagiTipsSize:
      name: live2d_takagiTipsSize
      label: 提示框大小
      type: text
      data-type: string
      default: "250x70"
    live2d_takagiFontSize:
      name: live2d_takagiFontSize
      label: 字体大小
      type: text
      data-type: string
      default: "12px"
    live2d_takagiToolFont:
      name: live2d_takagiToolFont
      label: 工具栏字体
      type: text
      data-type: string
      default: "14px"
    live2d_takagiToolLine:
      name: live2d_takagiToolLine
      label: 工具栏行高
      type: text
      data-type: string
      default: "20px"
    live2d_takagiToolTop:
      name: live2d_takagiToolTop
      label: 工具栏顶部边距
      type: text
      data-type: string
      default: "0px"
    live2d_takagiMinWidth:
      name: live2d_takagiMinWidth
      label: 显示看板娘的最大宽度
      type: text
      data-type: string
      default: "768px"
      description: '当页面小于指定宽度的时候，隐藏看板娘，输入disable则停用此功能'
    live2d_takagiEdgeSide:
      name: live2d_takagiEdgeSide
      label: 看板娘贴边方向
      type: text
      data-type: string
      default: "left:0"
      description: '使用绝对定位 left:0 就代表靠左'
    live2d_takagiDraggable:
      name: live2d_takagiDraggable
      label: 看板娘拖拽方案
      type: select
      data-type: string
      default: 'disable'
      options:
        - value: 'disable'
          label: 禁用拖拽
        - value: 'axis-x'
          label: 水平拖拽
        - value: 'unlimited'
          label: 自由拖拽
    live2d_takagiDraggableRevert:
      name: live2d_takagiDraggableRevert
      label: 松开鼠标还原拖拽位置
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    live2d_aboutPageUrl:
      name: live2d_aboutPageUrl
      label: 关于页地址
      type: text
      data-type: string
      default: ""
    live2d_screenshotCaptureName:
      name: live2d_screenshotCaptureName
      label: 看板娘截图文件名
      type: text
      data-type: string
      default: "live2d.png"
    live2d_style:
      name: live2d_style
      label: 额外CSS
      type: textarea
      data-type: string
      default: ""
      description: '额外CSS，请注意，最好最外层使用.takagi 以免污染其他css'